meta:
  title: Étlap - Zümmögő
  description: Tekintse meg aktuális árainkat.
  keywords: étlap, menu, árak, zümmögő
jsonld:
  '@context': https://schema.org
  '@type': Menu
  name: Zümmögő Menu
  url: https://zummogo.hu/hu/menu
hero:
  title: Étel-Ital Kínálatunk
  subtitle: Zümmögő
  short_summary: Szeretettel készítve, örömmel tálalva.
  summary: Tekintse meg aktuális árainkat. Étlapunk változatos fogásokat kínál, amelyek minden ízléshez és költségvetéshez igazodnak.
  buttons:
    - text: Asztalfoglalás
      link: /hu/contact
      type: primary
sections:
  - title: Wrap kínálatunk
    items:
      - name: Tépett Kacsás
        price: 2890 Ft
        description: Szaftos, omlós sült kacsa tépve, különleges szilvalekváros mustárral megbolondítva. Friss rukkolával és ropogós uborkával töltve, tortillába tekerve – édes, pikáns és telt ízek harmóniája.
        image: /static/img/68c3df7642da1c20b8c3ae3c.webp
      - name: Avokádós-Lazacos
        price: 3190 Ft
        description: Selymes avokádókrém, prémium füstölt lazac és friss rukkola találkozása egy könnyű tortillában. Uborkaszeletek és savanyított lilahagyma gondoskodnak a frissességről, míg a pirított napraforgómag roppanós textúrát ad hozzá. Igazi ínyenc, frissítő és tápláló választás.
        image: /static/img/68c3df7142da1c20b8c3ae37_masolata.webp
      - name: Aszalt Paradicsomos-Tojásos
        price: 2390 Ft
        description: Friss, mediterrán ízek egy könnyű, mégis laktató wrapben. Lágy tortilla töltve krémes hummusszal, főtt tojással, bébispenóttal és morzsolt fetával. Az aszalt paradicsom olajával és cayenne fűszerrel kapja meg az intenzív, enyhén pikáns karakterét. Egészséges, ízgazdag választás, ha valami frisset és különlegeset ennél.
        image: /static/img/68c3df7142da1c20b8c3ae39.webp
      - name: Falafel
        price: 2290 Ft
        description: Ropogós falafel, friss salátalevelek, magyar paradicsom és uborka találkozik a krémes tahini öntettel. A savanyított lilahagyma és a gránátalma pedig extra frissességet és izgalmas ízt ad minden falatnak. Könnyű, mégis laktató választás bármelyik napszakban!
        image: /static/img/68c3df7642da1c20b8c3ae3f_1.webp
  - title: Szendvics kínálatunk / Saláta boxok
    items:
      - name: Prosciutto-Sajtos Ciabatta
        price: 2590 Ft
        description: Ropogós ciabatta töltve selymes brie sajttal és ízletes prosciutto sonkával. Szárított paradicsom és friss rukkolalevelek gazdagítják az ízélményt, így minden falat mediterrán harmóniát nyújt. Laktató, mégis könnyed választás bármely étkezéshez.
      - name: Caprese Ciabatta
        price: 2390 Ft
        description: Olasz klasszikus újragondolva... ropogós ciabattában lágy mozzarella, érett paradicsom és friss bazsalikomlevél találkozik. Pesto és balzsamecet teszi teljessé ezt a mediterrán ízélményt. Könnyű, frissítő és mindig időtálló választás.
      - name: Csirkés-Pesztós Ciabatta
        price: 2490 Ft
        description: Ropogós ciabattába töltött grillezett csirkemell, krémes pesto és olvadt edámi sajt. Friss paradicsom, rukkolalevelek és intenzív ízű szárított paradicsom teszi gazdaggá ezt a mediterrán hangulatú szendvicset. Laktató, mégis könnyed választás bármely étkezéshez.
      - name: Avokádókrémes box
        price: 2490 Ft
        description: Friss lollo saláta, szeletelt tojás, paradicsom és uborka frissessége találkozik a selymes avokádókrémmel. Ropogós ciabatta szeletekkel tálalva, könnyű, tápláló és ízletes választás bármely napszakra.
      - name: Tojáskrémes box
        price: 2590 Ft
        description: Friss lollo saláta, avokádó szeletek, paradicsom és uborka frissessége találkozik a selymes tojáskrémmel. Ropogós ciabatta szeletekkel tálalva, könnyű, tápláló és ízletes választás bármely napszakra.
  - title: Kávék
    items:
      - name: Ristretto
        price: 650 Ft
        image: /static/img/image_67213825_JPG.JPG
      - name: Espresso
        price: 690 Ft
        image: /static/img/IMG_9669.webp
      - name: Espresso Macchiato
        price: 790 Ft
      - name: Double Espresso
        price: 1190 Ft
      - name: Americano
        price: 790 Ft
      - name: Cortado
        price: 890 Ft
      - name: Cappuccino
        price: 990 Ft
      - name: Flat White
        price: 1190 Ft
      - name: Latte Macchiato
        price: 1090 Ft
      - name: Iced Coffee
        price: 1390 Ft
  - title: Matcha/Chai kínálatunk
    items:
      - name: Matcha Latte
        price: 1290 Ft
        image: /static/img/image_67164673.webp
      - name: Iced Matcha Latte
        price: 1390 Ft
        image: /static/img/IMG_4424_1.jpeg
      - name: Epres Matcha Latte
        price: 1490 Ft
      - name: Mangós Matcha Latte
        price: 1490 Ft
      - name: Epres Iced Matcha latte
        price: 1590 Ft
      - name: Mangós Iced Matcha Latte
        price: 1590 Ft
      - name: Chai latte
        price: 1390 Ft
      - name: Dirty Chai latte
        price: 1790 Ft
      - name: Espresso Tonic
        price: 1790 Ft
      - name: Nutella latte
        price: 1690 Ft
      - name: Fagyis Jegeskávé
        price: 1990 Ft
  - title: Limonádé/Forró csoki
    items:
      - name: Klasszikus Limonádé
        price: 1550 Ft
      - name: Bodzás Limonádé
        price: 1550 Ft
      - name: Epres Limonádé
        price: 1550 Ft
      - name: Málnás Limonádé
        price: 1550 Ft
      - name: Mangós Limonádé
        price: 1550 Ft
      - name: Görögdinnyés Limonádé
        price: 1550 Ft
      - name: Levendulás Limonádé
        price: 1550 Ft
      - name: Tejcsokoládés Forró Csoki
        price: 1550 Ft
      - name: Fehércsokoládés Forró Csoki
        price: 1550 Ft
      - name: Étcsokoládés Forró Csoki
        price: 1550 Ft
gallery:
  - /static/img/IMG_9614.webp
  - /static/img/IMG_5360.webp
  - /static/img/image_67213825_dup.webp
  - /static/img/image_123650291_10.webp
  - /static/img/8E97A229-25D0-4D3E-9285-B1EDD7E28521.webp
  - /static/img/IMG_3695.webp
cta_section:
  title: Látogass el hozzánk!
  text: Várjuk szeretettel!
  buttons:
    - text: Kapcsolat
      link: /hu/contact
      type: primary
nav:
  home: Kezdőlap
  menu: Étlap
  about: Rólunk
  contact: Kapcsolat
